# fly.toml app configuration file generated for voyager-db on 2023-06-02T15:30:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "voyager-db"
primary_region = "cdg"

[env]
  PRIMARY_REGION = "cdg"

[[mounts]]
  source = "pg_data"
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "1m0s"
    timeout = "10s"
    path = "/flycheck/vm"

[metrics]
  port = 9187
  path = "/metrics"

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432

[[vm]]
  size = "shared-cpu-4x"
  memory = "2gb"
